name: 'Trim-CI'
description: 'Slashes CI waste by reporting real-time run costs'
author: 'Anvean Technologies'
inputs:
  github-token:
    description: 'Required for PR comments'
    required: true
    default: ${{ github.token }}
  force-billing:
    description: "Force billing calculation even for public repositories"
    required: false
    default: "false"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: "dollar-sign"
  color: "green"

